### ISSUE TITLE
Inconsistent results with LLM.int8() and SmoothQuant papers

### ISSUE THREAD

**Issue by fxmarty** [facebookresearch/LLM-QAT#19]
Hi,

Rereading LLM-QAT paper, it appears to me that the results presented as RTN (post-training quantization, round to nearest) are inconsistent with LLM.int8() and SmoothQuant claims about outliers in LLMs.

![image](https://github.com/facebookresearch/LLM-QAT/assets/9808326/7cc2bbd2-0448-4460-a115-9979dda8eb82)

SmoothQuant claim is that RTN is not enough to perserve prediction quality for W8A8 quantization which seem to contradict LLM-QAT results.

One explanation I could see is that the outlier issue is not as bad for llama as it once was for OPT or BLOOM.

What do you think?

**Comment by liuzechun** [comment]
Hi, Thanks for this interesting observation. 

Yes, I believe this may due to the architecture difference as well as the model size difference. From the LLM.int8() paper, the smaller the model is, the less affected it is by outliers.: 
<img width="894" alt="image" src="https://github.com/facebookresearch/LLM-QAT/assets/26427257/424054b7-abbc-4841-a67f-d51f2eb456e2">
And the results also suggested that in OPT-6.7B and 13B there is some slight degradation in ppl with vector quantization, not very large. (0.08 in 6.7B case and 1.02 in 13B case.) 

Since SmoothQuant did most of experiments on OPT-175B model, I think the outlier effect might be much larger in such huge model. 

In addition, we do observe some outliers in LLaMA, but it works fine with 8-bit quantization.
